export const apiAdminRoutes = {
    ADMIN_USERS: '/admin/users',
    ADMIN_NOUNUS_PENDING: '/admin/nounus/pending',
    ADMIN_NOUNU_CERTIFY: '/admin/nounus',
    ADMIN_STATS: '/admin/stats',
    ADMIN_USER_DELETE: '/admin/users',
    ADMIN_USER_RESTORE: '/admin/users',
    ADMIN_SETTINGS: '/admin/settings',
    ADMIN_TYPE_PARAMETERS: '/admin/type-parameters',
    ADMIN_PARAMETERS: '/admin/parameters',
    ADMIN_PERMISSIONS: '/admin/permissions',
    ADMIN_ROLE_PERMISSIONS: '/admin/roles',
    ADMIN_JOBS: '/admin/jobs',
    ADMIN_PARENTS: '/admin/parents',
    ADMIN_PAYMENTS: '/admin/payments',
    ADMIN_CHATS: '/admin/chats',
    ADMIN_CHATS_UNREAD_COUNT: '/admin/chats/unread-count',
    ADMIN_NOUNUS_LIST: '/admin/nounus',
    ADMIN_USER_DETAIL: '/admin/users',
    ADMIN_SUBSCRIPTIONS: '/admin/subscriptions',
    ADMIN_NOUNU_PAY: '/admin/nounus/pay',
    ADMIN_NOUNU_PAYMENTS: '/admin/nounus',
    ADMIN_SUB_ADMINS: '/admin/sub-admins',
    ADMIN_CHAT_SEND_MESSAGE: '/admin/chats',
    ADMIN_PACKS: '/admin/packs',
    ADMIN_PACKS_ACTIVE: '/admin/packs/active',
}
