export const apiSettingRoutes = {
    SETTING_ALL: '/parameters',
    SETTING_AGE_OF_CHILDRENS: '/parameters/slug/age-des-enfants',
    SETTING_SPECIFIC_NEEDS: '/parameters/slug/besoins-specifique',
    SETTING_HOUSEKEEPER: '/Parameters/slug/aide-menagere',
    SETTING_TYPE_OF_SERVICE: '/Parameters/slug/garde-d-enfants',
    SETTING_LANGUAGE: '/Parameters/slug/langues-parlees',
    SETTING_LOCALIZATION: '/Parameters/slug/localisations',
    SETTING_CHILD_CARE: '/Parameters/slug/age-des-enfants',
    SETTING_SERVICE_FREQUENCY: '/Parameters/slug/frequence-de-services',
    SETTING_DESIRED_TIMES: '/Parameters/slug/horaires-souhaites',
    SETTING_PAYMENT_TERMS: '/Parameters/slug/mode-de-paiement',
    SETTING_SPECIFIC_SKILLS: '/Parameters/slug/competences-specifiques',
    SETTING_CERTIFICATIONS: '/Parameters/slug/certifications',
    SETTING_TASKS: '/Parameters/slug/taches',
    SETTING_EQUIPMENT: '/Parameters/slug/equipement-menager',
    SETTING_AVAILABILITY_OF_SERVICE_PROVIDER: '/Parameters/slug/disponibilite-du-prestataire',
    SETTING_CRITERIA_CANDIDATE: '/Parameters/slug/criteres-de-selection-des-candidats',
    SETTING_TYPE_OF_SERVICE_PROVIDER: '/Parameters/slug/type-de-services',
    
}