export const apiSettingRoutes = {
    SETTING_ALL: '/parameters',
    SETTING_AGE_OF_CHILDRENS: '/parameters/slug/age-des-enfants',
    SETTING_SPECIFIC_NEEDS: '/parameters/slug/besoins-specifique',
    SETTING_HOUSEKEEPER: '/parameters/slug/aide-menagere',
    SETTING_TYPE_OF_SERVICE: '/parameters/slug/garde-d-enfants',
    SETTING_LANGUAGE: '/parameters/slug/langues-parlees',
    SETTING_LOCALIZATION: '/parameters/slug/localisations',
    SETTING_CHILD_CARE: '/parameters/slug/age-des-enfants',
    SETTING_SERVICE_FREQUENCY: '/parameters/slug/frequence-de-services',
    SETTING_DESIRED_TIMES: '/parameters/slug/horaires-souhaites',
    SETTING_PAYMENT_TERMS: '/parameters/slug/mode-de-paiement',
    SETTING_SPECIFIC_SKILLS: '/parameters/slug/competences-specifiques',
    SETTING_CERTIFICATIONS: '/parameters/slug/certifications',
    SETTING_TASKS: '/parameters/slug/taches',
    SETTING_EQUIPMENT: '/parameters/slug/equipement-menager',
    SETTING_AVAILABILITY_OF_SERVICE_PROVIDER: '/parameters/slug/disponibilite-du-prestataire',
    SETTING_CRITERIA_CANDIDATE: '/parameters/slug/criteres-de-selection-des-candidats',
    SETTING_TYPE_OF_SERVICE_PROVIDER: '/parameters/slug/type-de-services',
    
}